name: CI
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v3

            - name: Install system dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf libxdo-dev

            - name: Install Rust stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true

            - name: Set up cargo cache
              uses: actions/cache@v3
              continue-on-error: false
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      frontend/target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: ${{ runner.os }}-cargo-

            - name: Setup PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Setup node and Cache .pnpm-store
              uses: actions/setup-node@v3
              with:
                  node-version: latest
                  cache: "pnpm"
                  cache-dependency-path: ./frontend/pnpm-lock.yaml

            - name: Install dependencies
              working-directory: ./frontend
              run: pnpm install

            - name: Build 🔧
              working-directory: ./frontend
              run: pnpm build:tauri
